# Generated by Django 4.2 on 2023-04-13 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('task', models.CharField(blank=True, max_length=60, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
